<?php


namespace App\Controller;


use App\Model\Document\RecipesDocument;
use App\Model\DocumentLocator;

class RecipesController extends AppController
{
    /**
     * @var RecipesDocument
     */
    private $Recipes;

    /**
     * @inheritDoc
     */
    public function initialize(): void
    {
        $this->Recipes = new RecipesDocument();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * Index action
     *
     * @return void
     */
    public function index()
    {
        $Model = new RecipesDocument();
        $recipes = $Model->getAll(true);
        $this->set(compact('recipes'));
    }

    /**
     * View method
     *
     * @param string|null $id Contact id.
     * @return \Cake\Http\Response|null|void Renders view
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $recipe = $this->Recipes->get($id);

        $this->set(compact('recipe'));
    }
}
