<?php


namespace App\Controller;


use App\Model\Document\RecipesDocument;
use App\Model\DocumentLocator;

class RecipesController extends AppController
{
    /**
     * @inheritDoc
     */
    public function initialize(): void
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * Index action
     *
     * @return void
     */
    public function index()
    {
        $Model = new RecipesDocument();
        $recipes = $Model->getAll(true);
        $this->set(compact('recipes'));
    }
}
